inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - '*.gemspec'
  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false
  # IgnoreComments: true -- somehow did not recognized?..

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120

# I'm big fan of and/or for flow control
Style/AndOr:
  Enabled: false

# Somehow he didn't recognize that module TimeMath is documented...
Style/Documentation:
  Enabled: false

# Everything else is just my personal style
Style/SingleLineBlockParams:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/ParallelAssignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

Lint/BooleanSymbol:
  Enabled: false

# RSpec
Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Security/YAMLLoad:
  Exclude:
    - 'spec/**/*'
